import React from 'react';
import './Studio.css';
function Icon({name}) {
 const paths={screen:<><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4M3 8h18"/></>,cursor:<path d="m5 3 14 10-7 1-3 7Zm8 11 5 6"/>,chat:<><path d="M20 15a3 3 0 0 1-3 3H9l-5 3V7a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3Z"/><path d="M8 9h8m-8 4h5"/></>,spark:<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>,coffee:<path d="M4 8h13v8a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4ZM17 9h2a3 3 0 0 1 0 6h-2M7 2v3m5-3v3"/>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,pin:<><path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="9" r="2"/></>,bag:<><rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12c6 4 12 4 18 0m-9 0v4"/></>,file:<path d="M14 2H5v20h14V7Zm0 0v6h5M8 12h8m-8 4h6"/>,heart:<path d="M12 21 3 12C-3 4 7-1 12 6c5-7 15-2 9 6Z"/>,check:<path d="m5 12 4 4L19 6"/>};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function Label({number,children}){return <p className="p-label"><span>{number}</span>{children}</p>}
const work=[['screen','화면을 설계하고','UI/UX 디자인','사용자가 자연스럽게 이해하는 직관적이고 일관된 디지털 경험을 만듭니다.'],['cursor','경험을 연결하고','콘텐츠 · 서비스 · UX','브랜드의 이야기를 콘텐츠와 서비스로 연결하며, 더 나은 경험을 구체화합니다.'],['chat','함께 완성해요','프로젝트 · 커뮤니케이션','동료, 고객사와 생각을 나누며 프로젝트의 시작부터 완성까지 함께합니다.']];
export default function Studio(){return <main id="content" className="recruitment playful">
<header className="p-header"><img src="/imgs/로고.svg" alt="VW"/><span>DIGITAL BRANDING DIRECTORS</span><span className="p-hiring"><i/> WE’RE HIRING</span></header>
<section className="p-hero"><p className="p-kicker">HELLO, OUR NEXT TEAMMATE!</p><h1>좋은 동료와 만드는<br/><span>다음의 디자인.</span><Icon name="spark"/></h1><p className="p-lead">서로 다른 생각이 만나, 더 좋은 경험이 되도록.<br/><strong>브이더블유에서 당신의 다음을 함께 그려요.</strong></p><div className="p-chips"><span>디지털 · UI/UX 디자이너</span><span>신입 · 경력</span><span>정규직</span></div><div className="p-illustration"><img src="/imgs/studio-characters.png" alt="노트북, 연필, 태블릿으로 함께 디자인하는 세 명의 2D 디자이너 캐릭터"/><span className="p-note">Different minds.<br/>Better together. <Icon name="heart"/></span></div><a className="p-hero-link" href="#studio-apply" onClick={e=>{e.preventDefault();document.getElementById('studio-apply').scrollIntoView({behavior:'smooth'})}}>우리의 다음 동료가 되어주세요 <span>↓</span></a></section>
<div className="p-ribbon"><span>THINK TOGETHER</span><Icon name="spark"/><span>DESIGN BETTER</span><Icon name="spark"/><span>GROW WITH VW</span></div>
<section className="p-section p-about"><Label number="01">A LITTLE ABOUT US</Label><h2>혼자서는 떠올리지 못한 것들.<br/>우리는 <em>함께</em> 발견해요.</h2><p>우리는 브랜드를 이해하는 것에서 출발합니다.<br/>무엇을 말할지, 어떻게 연결할지, 어떤 경험을 남길지.<br/>브이더블유는 그 질문을 디자인으로 풀어갑니다.</p><p>명확한 생각과 섬세한 실행을 더해줄<br/>당신만의 시선을 기다립니다.</p><span className="p-about-doodle"><Icon name="chat"/><Icon name="spark"/></span></section>
<section className="p-section p-work"><Label number="02">WHAT WE’LL MAKE</Label><h2>우리, 이런 일을 해요<span className="p-coral">.</span></h2><div className="p-work-grid">{work.map(([icon,title,sub,body],i)=><article key={icon}><div className="p-work-top"><Icon name={icon}/><span>0{i+1}</span></div><p className="p-card-sub">{sub}</p><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="p-section p-fit"><Label number="03">IS THIS YOU?</Label><h2>완벽한 정답보다,<br/>당신의 <em>생각이 궁금해요.</em></h2><div className="p-fit-grid"><div><h3><Icon name="check"/> 이런 동료를 기다려요</h3><ul><li>경력무관 · 신입 및 경력 지원 가능</li><li>전문대 졸업 이상의 학력</li><li>디지털 UX 디자인 경험</li><li>원활한 커뮤니케이션과 협업 능력</li></ul></div><div className="p-plus"><span className="p-plus-tag">NICE TO HAVE</span><h3>이런 경험은 더 반가워요!</h3><ul><li>AI 도구를 디자인 업무에 활용하실 수 있는 분</li><li>디지털 에이전시 경력이 있는 분</li></ul><Icon name="spark"/></div></div></section>
<section className="p-section p-life"><Label number="04">A GOOD DAY AT VW</Label><h2>몰입할 시간도,<br/>잠깐의 쉼표도 필요하니까.</h2><div className="p-perks"><div><Icon name="sun"/><h3>눈치 없이, 리프레시</h3><p>자유로운 휴가문화<br/>연차 · 반차 · 경조휴가</p></div><div><Icon name="coffee"/><h3>일상 속 작은 충전</h3><p>음료와 간식 제공<br/>노동절 휴무</p></div><div><Icon name="heart"/><h3>내일도 든든하게</h3><p>퇴직연금<br/>함께 만드는 일상</p></div></div><figure className="p-office"><img src="/imgs/vw-office.jpg" alt="브이더블유 회사명과 VW 로고가 보이는 사무실 입구 전체 사진"/><figcaption><Icon name="pin"/><span>OUR STUDIO IN SEONGSAN-DONG</span><span>당신의 자리가 될 곳 ↗</span></figcaption></figure></section>
<section className="p-section p-conditions"><Label number="05">THE LITTLE DETAILS</Label><h2>함께 일할 조건을 알려드려요.</h2><dl>{[['bag','고용형태','정규직','수습 3개월'],['spark','급여','연봉 3,000~5,000만원','면접 후 결정'],['clock','근무시간','09:30 — 18:30','주 5일 (월~금) · 탄력근무제'],['pin','근무장소','서울 마포구 성산동','월드컵로32길 24, 중보빌딩 3층 / 6호선 마포구청역 도보 4분 이내']].map(([icon,label,title,detail])=><div key={label}><dt><Icon name={icon}/>{label}</dt><dd><strong>{title}</strong><span>{detail}</span></dd></div>)}</dl></section>
<section className="p-section p-apply" id="studio-apply"><Label number="06">YOUR NEXT CHAPTER</Label><span className="p-apply-star"><Icon name="spark"/></span><h2>다음 이야기는,<br/><span>당신과 함께.</span></h2><p className="p-apply-intro">멋진 결과물 뒤에 있는 당신의 생각을 보여주세요.</p><ol className="p-steps">{[['file','서류전형'],['chat','면접'],['heart','최종합격']].map(([icon,text],i)=><li key={text}><Icon name={icon}/><small>STEP 0{i+1}</small><strong>{text}</strong></li>)}</ol><div className="p-apply-info"><div><h3>보내주실 자료</h3><p>이력서 · 경력기술서 · 포트폴리오</p><small>경력기술서에 희망연봉을 기재해주세요.</small></div><div><h3>지원 방법 및 기간</h3><p>잡코리아 이력서 양식으로 즉시지원</p><strong>2026.09.10 — 2026.10.10</strong></div></div><p className="p-fineprint">면접 일정은 추후 개별 안내됩니다.<br/>채용 일정은 회사 사정에 따라 변경되거나 조기 마감될 수 있습니다.<br/>지원서에 허위 사실이 발견될 경우 채용이 취소될 수 있습니다.</p><footer className="p-footer"><div><img src="/imgs/로고.svg" alt="VW"/><span>㈜브이더블유<br/>DIGITAL BRANDING DIRECTORS</span></div><a href="https://www.v-w.co.kr/" target="_blank" rel="noopener noreferrer">우리의 작업 보기 ↗</a></footer></section>
</main>}
